name: Dev publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Extract PACKAGE_VERSION
        run: echo ::set-env name=PACKAGE_VERSION::$(node -p -e "require('./package.json').version")
      - name: Publish
        if: contains(env.PACKAGE_VERSION, 'dev') == true
        run: |
          yarn install --frozen-lockfile
          yarn build
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}
      - name: Discord notification
        if: contains(env.PACKAGE_VERSION, 'dev') == true
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEV_ANN }}
          DISCORD_EMBEDS: toJSON("{"embed":{"title":"New dev version `${{ env.PACKAGE_VERSION }}` has been released.","description":"Changelog available [here](https:\/\/github.com\/NRCHKB\/node-red-contrib-homekit-bridged\/commits\/dev\/CHANGELOG.md)","url":"https:\/\/github.com\/NRCHKB\/node-red-contrib-homekit-bridged\/tree\/dev","color":9371648,"fields":[{"name":"How to install","value":"1. Stop node-red\n2. Backup `~\/.node-red` folder\n3. `cd ~\/.node-red`\n4. `npm i node-red-contrib-homekit-bridged@${{ env.PACKAGE_VERSION }}`\n5. Start node-red"}]}}")
        uses: Ilshidur/action-discord@master
