name: Dev publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm i -g yarn
          yarn install --frozen-lockfile
          yarn build
          yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Extract PACKAGE_VERSION
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Publish
        if: contains(steps.package-version.outputs.current-version, 'dev') == true
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile
          yarn build
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEV_ANN }}
          DISCORD_EMBEDS: "{\"embed\":{\"title\":\"New dev version `${{ env.PACKAGE_VERSION }}` has been released.\",\"description\":\"Changelog is available [here](https:\/\/github.com\/NRCHKB\/node-red-contrib-homekit-bridged\/commits\/dev\/CHANGELOG.md)\",\"url\":\"https:\/\/github.com\/NRCHKB\/node-red-contrib-homekit-bridged\/tree\/dev\",\"color\":9371648,\"fields\":[{\"name\":\"How to install\",\"value\":\"1. Stop node-red\r\n2. Backup `~\/.node-red` folder\r\n3. `cd ~\/.node-red`\r\n4. `npm i node-red-contrib-homekit-bridged@${{ env.PACKAGE_VERSION }}`\r\n5. Start node-red\"}]}}"
        uses: Ilshidur/action-discord@master
      - name: Discord error notification
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ERROR }}
          DISCORD_EMBEDS: "{\"embed\":{\"title\":\"Dev version `${{ env.PACKAGE_VERSION }}` failed to be released.\",\"description\":\"Changelog is available [here](https:\/\/github.com\/NRCHKB\/node-red-contrib-homekit-bridged\/commits\/dev\/CHANGELOG.md)\",\"url\":\"https:\/\/github.com\/NRCHKB\/node-red-contrib-homekit-bridged\/tree\/dev\",\"color\":9371648,\"fields\":[{\"name\":\"How to install\",\"value\":\"1. Stop node-red\r\n2. Backup `~\/.node-red` folder\r\n3. `cd ~\/.node-red`\r\n4. `npm i node-red-contrib-homekit-bridged@${{ env.PACKAGE_VERSION }}`\r\n5. Start node-red\"}]}}"
        uses: Ilshidur/action-discord@master
